name: tour_package_meet
description: Guide that helps you to present your app and its features in a beautiful, simple and customizable way.
version: 1.2.1
homepage: https://github.com/patelmeet341993/tour_package_meet

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:


